### ISSUE TITLE
Data in MakeUDPArray not seen in UDP packet

### ISSUE THREAD

**Issue by DrychronRed** [is-centre/udp-ue4-plugin-win64#13]
Sole Rebel Soul, whom I am working with, contacted you in YouTube, and I wrote this message there as well, but I later saw your comment that it's better to treat as an actual issue, so I'm doing that now (sorry).

Sole is building the game using Blueprint.  I'm a C++ programmer, but he is in London and I am in Los Angeles.  This version is sending data on every event tick to the correct port - I can see it in Wireshark (the diagnostic app), but the correct data does not seem to be in the packet.   We're tried to create fixed data that we can recognize (1,2,3,4 etc.). Somehow either the UDPSender() is not correctly stuffing the values Sole is putting in the structure in MakeUDPArray into the array and so what's being sent is not correct, or Sole is doing it wrong, which from his screenshots, seems pretty straight-forward.  We would appreciate any help you are willing to give.  This plugin is EXACTLY what we need!!!  THANK YOU.  A reminder that this is UE5.1

**Comment by DrychronRed** [comment]
I don't know how to send his BP code except for a screenshot, but he'd have to do that.  I can send the output of a Wireshark packet, but I doubt that helps.  Let me know what I can do to help make it obvious what is wrong!

**Comment by extall** [comment]
1. If possible, please share screenshots. They just need to depict the initialization and data sending parts.
2. It might be a firewall issue somewhere along the route. So I need more information on the route. Are you using long-distance communication? And besides that, what are you unpacking the data with (besides sniffing packets with wireshark)?

**Comment by DrychronRed** [comment]
I will ask Sole to post screenshots.  I'm waiting for him to respond to my message.  His initialization seems right though - the port is correct, the IP is loopback (127.0.0.1).  He sends me versions of his game.  I run Wireshark on my system and then run his game and immediately start getting packets in Wireshark on that port.  I was initially writing a SimTools plugin to receive the packets but I stopped when I realized that the packets didn't have the right data in them.  UDP packets can certainly leave the transmitter and be received by anything so Wireshark should be a valid way to do that - I'm just looking at the data.  Regarding a firewall, I'm getting the packets when the game runs and don't get the packets when the game stops running- and I've never heard of a firewall modifying packets only blocking them.

Hope this helps (prior to screenshots).  I sincerely appreciate your assistance with this and your quick response is awesome!

I do understand why the screenshots are valuable! THANKS!

**Comment by DrychronRed** [comment]
I have a question.  The structure is set up for 20 floats and 3 uints.  If he "assigns" 2 floats (roll and pitch) and nothing else, will that be ok?  The rest is empty (zero) or random data?  I just want to make sure that only sending 2 floats would work.  If he wanted to send 2 floats and 1 uint would he have to send 2 floats of valid data then 18 floats of random/zero/something else and then send the 1 uint, or can he just send 2 floats and 1 uint?  Sorry, my BP knowledge lacks - this question may be lame but I'm just trying to understand.

**Comment by trevorhill77** [comment]
![Level Blueprint](https://user-images.githubusercontent.com/37465010/215845589-cde86163-5d0b-49d9-8c45-e94f4d8b88fc.png)
Hello! I'm Sole Rebel Soul on Youtube. Thanks for sorting the plugin for 5.1 so quickly.

Attached is the level blueprint I've setup.

**Comment by DrychronRed** [comment]
> 

Extall would you mind giving us a Blueprint screenshot of sending maybe some static float values so that I can confirm the data is going through in Wireshark, and I can certainly make a Python or C++ receiver if you like, but just seeing 1.0, 2.0, 3.0, 40. and so on going through the UDP (and maybe 1,2,3 going through the Uints) that would be fantastic.

Honestly if you can help us get the data to work for UDP (most critically to send UDP data out of UE5.1, but later on to receive values from UDP being sent from me to the game) I can send you some $.

**Comment by extall** [comment]
Three points.
- Yes, you can use just a few inputs to the structure (e.g., utilize just 3 float inputs), leaving others empty. They will just be sent as zeros.
- This is an open source project, we are not accepting $. Outsourcing our services is a separate discussion.
- I have assigned my doctoral student to this issue. He has been working recently on UDP comms and may have a solution for you.

**Comment by DrychronRed** [comment]
@extall Thank you in all cases.  I will ask Sole to try sending just 3 floats (again), but having them come in as zero might not be that useful for testing.  I apologize if I offended anyone by suggesting a financial contribution.  I won't bring it up again. If we indeed get to where we look for outsourcing in a more substantial way, I'll contact you separately.  Thank you very much for assigning someone to assist us.  I am excited, as this working will be huge for us in this project and new ones!  My daughter's in a PhD program.  I didn't make it as far myself.  Thanks again!

**Comment by trevorhill77** [comment]
We got a crash on startup when the input is a static float. Is that expected behaviour?

**Comment by extall** [comment]
Crash? No, not really. This plugin is known to be quite stable which is the reason why it became popular. I mean, there are some edge cases where it might not work, but it should not crash.

Saleh promised to have a look. He will get back to you.

**Comment by saleh9292** [comment]
@trevorhill77  @DrychronRed 
I can confirm that the plugin works with UE5.1, I have created a sample project with a UDP sender and receiver as follows:

![image](https://user-images.githubusercontent.com/22989635/216317765-58d00ffa-91ce-45c4-8e10-c8de1e0def23.png)

![image](https://user-images.githubusercontent.com/22989635/216317712-4fafa8bb-6461-4f3d-a2dd-180ca16861f6.png)

Did you try to receive the data with something other than Wireshark?
If you are trying to capture the data on a Windows local machine using Wireshark, make sure you are using the "Adapter for loopback traffic capture" https://stackoverflow.com/questions/5847168/wireshark-localhost-traffic-capture 

You can use this python script tp recive and parse the data:

Source:https://pythontic.com/modules/socket/udp-client-server-example
I have modifed the script to decode the recived meassge as well.

```
import socket
import struct

localIP = "127.0.0.1"

localPort = 4123

bufferSize = 1024

# Create a datagram socket

UDPServerSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)

# Bind to address and ip

UDPServerSocket.bind((localIP, localPort))

print("UDP server up and listening")

# Listen for incoming datagrams

while (True):
    bytesAddressPair = UDPServerSocket.recvfrom(bufferSize)

    message = bytesAddressPair[0]

    address = bytesAddressPair[1]

    clientIP = "Client IP Address:{}".format(address)

    data = struct.unpack_from('f' * 20 + 'B' * 3, message, offset=0)

    print(data)

```

**Comment by DrychronRed** [comment]
Saleh9292,

Thank you very much for your efforts.  Although I have Wireshark using the loopback address adapter and Wireshark is working fine, I am also using your python script.   Sole (Trevor) is pursuing the game Blueprints and was able to get around the crash and he's in the UK so he's done for the day and we'll try again tomorrow.  Hopefully we can confirm it's working tomorrow.

Cheers,
@DrychronRed


> @trevorhill77  @DrychronRed  I can confirm that the plugin works with UE5.1, I have created a sample project with a UDP sender and receiver as follows:
> 
> ![image](https://user-images.githubusercontent.com/22989635/216317765-58d00ffa-91ce-45c4-8e10-c8de1e0def23.png)
> 
> ![image](https://user-images.githubusercontent.com/22989635/216317712-4fafa8bb-6461-4f3d-a2dd-180ca16861f6.png)
> 
> Did you try to receive the data with something other than Wireshark? If you are trying to capture the data on a Windows local machine using Wireshark, make sure you are using the "Adapter for loopback traffic capture" [https://stackoverflow.com/questions/5847168/wireshark-localhost-traffic-capture ](https://stackoverflow.com/questions/5847168/wireshark-localhost-traffic-capture%C2%A0)
> 
> You can use this python script tp recive and parse the data:
> 
> Source:https://pythontic.com/modules/socket/udp-client-server-example I have modifed the script to decode the recived meassge as well.
> 
> ```
> import socket
> import struct
> 
> localIP = "127.0.0.1"
> 
> localPort = 4123
> 
> bufferSize = 1024
> 
> # Create a datagram socket
> 
> UDPServerSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
> 
> # Bind to address and ip
> 
> UDPServerSocket.bind((localIP, localPort))
> 
> print("UDP server up and listening")
> 
> # Listen for incoming datagrams
> 
> while (True):
>     bytesAddressPair = UDPServerSocket.recvfrom(bufferSize)
> 
>     message = bytesAddressPair[0]
> 
>     address = bytesAddressPair[1]
> 
>     clientIP = "Client IP Address:{}".format(address)
> 
>     data = struct.unpack_from('f' * 20 + 'B' * 3, message, offset=0)
> 
>     print(data)
> ```

**Comment by DrychronRed** [comment]
@saleh9292 We have this working now - however I have a question or two - first let me say that Trevor isn't sure why his game was crashing.  He went through and made the Blueprint look like how you had it and it didn't crash anymore - however we both think he had set it up the same - so we don't know, which isn't the best but it seems to be solid now - we're getting both static floats and dynamic floats - the actual roll and pitch we need..  I knew when I saw 0x3F and 0x80 and 0x40 in the Wireshark data that it contained 1.0 and 2.0 float - in hex and was so happy.

So my remaining question is that I'm getting a packet of 95 bytes. Each float takes up 4 bytes - so 20 x 4 = 8 bytes.  That makes sense. Your python script uses the unpack function, and you're using "f" for floats (makes sense) but "B" for UINTS which doesn't make sense to me - "B" should be unsigned char, which is 8 bits - after the 80 bytes I have 15 bytes, which doesn't make sense. Even if you would have used "I"or "L" instead of "B" which would be UINTS, which I would have thought is correct, that would take up 4 bytes each or 12, but 80 plus 12 is 93 not 95.  So I'm a bit confused.  Can you set me straight?

Thank you very much for your assistance!  We are happy campers!

**Comment by saleh9292** [comment]
@DrychronRed I am glad that it worked for you. 
Using the default data structure of "20 floats plus 3 unit8" we get a message size of 83.
`print(len(message))` returns 83 in my case.
I am not sure where the 95 size is coming from. Are you including the UDP header size?

We're using the unit8 data type for the last three integers, unit8 is an 8-bit unsigned integer, which is why I used the "B" in Python.

If you intend to communicate between Unreal and Python, I recommend that you modify the data structure .﻿To make things easier, change the types to ones that are similar in size to those used in Pyton.i.e. to use the "I" or "L" instead of "B" by switching the unit 8 to
to unit 64 or int 64. We have given an example of how to change the data structure in the Readme file.

**Comment by extall** [comment]
Overall, I think the issue has been resolved, as the plugin is functioning as it should. One issue that remains is that of documentation for the plugin, however, it will be a different issue. For the moment, I will close this one.

**Comment by trevorhill77** [comment]
We solved most of the issue, but we're still getting a crash under certain circumstances.

![Image 2023-02-06 at 11 14 11 PM](https://user-images.githubusercontent.com/37465010/217901723-b84cec90-a1c4-435c-8caa-e1d42defd1f9.jpeg)
This setup works fine.

![Image 2023-02-06 at 11 25 34 PM](https://user-images.githubusercontent.com/37465010/217901884-d5618c31-d653-49ca-8423-a10dcae4c05f.jpeg)
However, we get a crash with this setup. Note the final float is in slot 20.

The crash message is as follows:
Assertion failed: Result
[file:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Public\UObject\Stack.h] [Line:361]


For our purposes, I think we are OK, for now at least, but just want to make you aware of the crash.
